set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm-256color:RGB"

set-option -g default-shell /bin/zsh

unbind C-b
set-option -g prefix M-a
bind M-a send-prefix

set-option -g base-index 1
set-option -g pane-base-index 1

set-option -g mouse on
set -g renumber-windows on

set-option -g history-limit 10000

bind c new-window -c "#{pane_current_path}" 
bind 'h' split-window  -c "#{pane_current_path}" 
bind 'v' split-window -h -c "#{pane_current_path}"

set -g set-clipboard on

set-option -s focus-events on
set-option -s escape-time 0
set-option -s extended-keys on

set-option -g status-position top

# YAZI Image support
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM


###############################################
#                  THEME
###############################################

ORANGE="#FF8F40"
RED="#D95757"
GREEN="#7FD962"
VIOLET="#DE32FB"
BG="#0D1017"
FG="#ffffff"
BLACK="#000000"

HALF_ROUND_OPEN="#(printf '\uE0B6')"
HALF_ROUND_CLOSE="#(printf '\uE0B4')"
FLAME_OPEN="#(printf '\uE0C2')"
FLAME_CLOSE="#(printf '\uE0C2')"

set-option -g status-style fg=${BLACK}
set -g status-bg default
set -g status-style bg=default

set-option -g status-left "\
#[bg=${VIOLET},fg=${BG}]\
 #S\
#[bg=default,fg=${VIOLET}]${HALF_ROUND_CLOSE}"

set-option -g status-justify absolute-centre

set-option -g status-right "\
#[bg=default,fg=${GREEN}]${HALF_ROUND_OPEN}\
#[bg=${GREEN},fg=${BG}]\
 #h "

set-option -g status-left-length 100
set-option -g status-right-length 100

set-option -g window-status-format "\
#[bg=default,fg=${ORANGE}]${HALF_ROUND_OPEN}\
#[fg=${BLACK},bg=${ORANGE}]#I:\
#W\
#[bg=default,fg=${ORANGE}]${HALF_ROUND_CLOSE}"

set-option -g window-status-current-format "\
#[bg=default,fg=${RED}]${HALF_ROUND_OPEN}\
#[fg=${BLACK},bg=${RED}]#I:\
#W\
#[bg=default,fg=${RED}]${HALF_ROUND_CLOSE}"


###############################################
#                  PLUGINS
###############################################

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Auto save and restore tmux sessions
# set -g @continuum-restore 'on'
# set -g @continuum-save-interval '15'  # save every 15 minutes

# Vim-Tmux Navigator keybindings
set -g @vim_navigator_mapping_left "C-Left"
set -g @vim_navigator_mapping_right "C-Right"
set -g @vim_navigator_mapping_up "C-Up"
set -g @vim_navigator_mapping_down "C-Down"
set -g @vim_navigator_mapping_prev ""

set -g @resurrect-dir '~/.config/tmux/sessions'
set -g @resurrect-save 'S'


unbind-key S
unbind-key R
unbind-key C-s
unbind-key C-r

# Vi-style copy mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key W command-prompt -p "Save session as:" \
  "run-shell \"\
    mkdir -p \$HOME/.config/tmux/sessions; \
    ~/.config/tmux/plugins/tmux-resurrect/scripts/save.sh; \
    cp \$HOME/.config/tmux/sessions/last \
       \$HOME/.config/tmux/sessions/%%.txt\
  \""


bind-key R command-prompt -p "Restore session:" \
  "run-shell \"\
    ln -sf \$HOME/.config/tmux/sessions/%%.txt \
           \$HOME/.config/tmux/sessions/last; \
    ~/.config/tmux/plugins/tmux-resurrect/scripts/restore.sh\
  \""

  # for neovim
set -g @resurrect-strategy-nvim 'session'

###############################################
#                  TPM INIT
###############################################

run '~/.config/tmux/plugins/tpm/tpm'
